### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by bfolberth** [Catapush/catapush-ios-swift-sdk-example#1]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'keypath sentTime not found in entity <NSSQLEntity MessageIP id=2>'

Any idea?

**Comment by felicedeluca** [comment]
Sorry, we have fixed the issue updating the pod version.
Please use 'pod update' to grab the latest catapush-lib version

**Comment by bfolberth** [comment]
Thank you. This works now. Though, I'am having issues with background messages. The messages are only shown if the app is in foreground (I get the connected messages each time opening the app). Notifications are not received if the app is in background. Now notification banners are shown. Any idea?

**Comment by chiarotto** [comment]
Have you followed the instructions in the **Prerequisites** section?

**Comment by bfolberth** [comment]
Yes.

**Comment by chiarotto** [comment]
when you have compiled the app, have you selected the provisioning profile associated to your app created on iTunes? Also check the app bundle id in XCode. It must be equals to id of your app in iTunes

**Comment by bfolberth** [comment]
Settings seems all good to me. Once I open the demo app, I get the "Catapush Connected" PopUp message - each time. Push notifications are not received when the app is in background.

**Comment by felicedeluca** [comment]
thank you, we have fixed an issue. Please fetch the new version.
It should work now.

**Comment by bfolberth** [comment]
Seems good now. Thank you.
