### ISSUE TITLE
Notification doesn't arrive when phone is on Do Not Disturb mode

### ISSUE THREAD

**Issue by felipeduarte-walmartlabs** [Catapush/catapush-ios-swift-sdk-example#3]
Hi team,

not sure how I could get in touch with you so decided to submit an issue. During the evaluation of the library we noticed that when the device is on DND the push notification doesn't arrive. WhatsApp for instance, we did a similar test and it arrived. Is it because WhatsApp keeps the XMPP connection open even on DND mode? Or do they have a special permission or use even use PushKit?

Thanks!

**Comment by catapush-team** [comment]
Hi, please send us a mail to support [at] catapush ]dot[ com
